from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.models import User, Role
from app.schemas.schemas import UserCreate, UserResponse, UserLogin, Token, GoogleLoginRequest
from app.core.security import verify_password, get_password_hash, create_access_token
from app.core.dependencies import get_current_user

router = APIRouter(prefix="/auth", tags=["Authentication"])

@router.post("/register", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def register(user_in: UserCreate, db: Session = Depends(get_db)):
    # Check if username or email already exists
    if db.query(User).filter(User.username == user_in.username).first():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username already registered"
        )
    if db.query(User).filter(User.email == user_in.email).first():
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered"
        )
    
    # Find role
    role = db.query(Role).filter(Role.name == user_in.role_name).first()
    if not role:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Role '{user_in.role_name}' does not exist"
        )
        
    hashed_password = get_password_hash(user_in.password)
    db_user = User(
        username=user_in.username,
        email=user_in.email,
        hashed_password=hashed_password,
        role_id=role.id
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

@router.post("/login", response_model=Token)
def login(user_in: UserLogin, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.username == user_in.username).first()
    if not user or not verify_password(user_in.password, user.hashed_password):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Incorrect username or password"
        )
    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Inactive user"
        )
        
    access_token = create_access_token(username=user.username, role=user.role.name)
    return {"access_token": access_token, "token_type": "bearer"}

@router.get("/me", response_model=UserResponse)
def get_me(current_user: User = Depends(get_current_user)):
    return current_user

@router.post("/google", response_model=Token)
def google_login(payload: GoogleLoginRequest, db: Session = Depends(get_db)):
    # Simulates verification of a Google OAuth2 token.
    # Accepts a mock string of "username:email@company.com" or falls back.
    parts = payload.credential.split(":")
    if len(parts) == 2:
        username, email = parts
    else:
        username = "google_user"
        email = "google_user@gmail.com"

    # Check if this email is already registered in the system
    user = db.query(User).filter(User.email == email).first()
    if not user:
        # Default Google Sign-ins to the 'Security Analyst' role
        role = db.query(Role).filter(Role.name == "Security Analyst").first()
        if not role:
            # Fallback to the first available role if missing
            role = db.query(Role).first()

        user = User(
            username=username,
            email=email,
            hashed_password=get_password_hash("GoogleOAuthAutoGeneratedPassSecure12!"),
            role_id=role.id
        )
        db.add(user)
        db.commit()
        db.refresh(user)

    # Issue standard JWT session token
    access_token = create_access_token(username=user.username, role=user.role.name)
    return {"access_token": access_token, "token_type": "bearer"}

