from sqlalchemy.orm import Session

from app.models import (
    Investigation,
    Employee,
    BehaviorBaseline
)
from app.models import BehaviorLog

# =====================================================
# Automatic Investigation Generation
# =====================================================

def generate_investigation(
    db: Session,
    employee_id: int,
    prediction: dict
):
    """
    Automatically create investigation for
    High/Critical insider threats.
    """

    if prediction["risk_level"] not in [
        "High",
        "Critical"
    ]:
        return None

    existing = (
        db.query(Investigation)
        .filter(
            Investigation.employee_id == employee_id,
            Investigation.status != "Closed"
        )
        .first()
    )

    if existing:
        return existing

    investigation = Investigation(

        employee_id=employee_id,

        incident_title="Potential Insider Threat Detected",

        threat_severity=prediction["threat_severity"],

        status="Open",

        assigned_analyst="Unassigned",

        investigation_notes="Automatically generated by AI Threat Detection Engine.",

        recommendation=prediction["recommendation"]

    )

    db.add(investigation)
    db.commit()
    db.refresh(investigation)

    return investigation


# =====================================================
# Dashboard
# =====================================================

def get_dashboard_investigations(db: Session):

    investigations = (
        db.query(Investigation)
        .order_by(
            Investigation.created_at.desc()
        )
        .all()
    )

    dashboard = []

    for item in investigations:

        employee = (
            db.query(Employee)
            .filter(
                Employee.id == item.employee_id
            )
            .first()
        )

        if not employee:
            continue

        dashboard.append({

            "id": item.id,

            "employee_id": employee.id,

            "employee_code": employee.employee_id,

            "full_name": employee.full_name,

            "department": employee.department,

            "role": employee.role,

            "incident_title": item.incident_title,

            "threat_severity": item.threat_severity,

            "status": item.status,

            "assigned_analyst": item.assigned_analyst,

            "created_at": item.created_at

        })

    return dashboard


# =====================================================
# Investigation Queue
# =====================================================

def get_active_investigations(db: Session):

    return (
        db.query(Investigation)
        .order_by(
            Investigation.created_at.desc()
        )
        .all()
    )


# =====================================================
# Investigation Details
# =====================================================

def get_investigation_details(
    db: Session,
    investigation_id: int
):

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    employee = (
        db.query(Employee)
        .filter(
            Employee.id == investigation.employee_id
        )
        .first()
    )

    if not employee:
        return None

    baseline = (
        db.query(BehaviorBaseline)
        .filter(
            BehaviorBaseline.employee_id == employee.id
        )
        .first()
    )

    return {

        "id": investigation.id,

        "employee_id": employee.id,

        "employee_code": employee.employee_id,

        "full_name": employee.full_name,

        "department": employee.department,

        "role": employee.role,

        "incident_title": investigation.incident_title,

        "threat_severity": investigation.threat_severity,

        "status": investigation.status,

        "assigned_analyst": investigation.assigned_analyst,

        "investigation_notes": investigation.investigation_notes,

        "recommendation": investigation.recommendation,

        "created_at": investigation.created_at

    }


# =====================================================
# Investigation Workflow
# =====================================================

def update_status(
    db: Session,
    investigation_id: int,
    status: str
):

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    investigation.status = status

    db.commit()
    db.refresh(investigation)

    return investigation

# =====================================================
# Activity Timeline
# =====================================================

def get_activity_timeline(
    db: Session,
    investigation_id: int
):

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    log = (
        db.query(BehaviorLog)
        .filter(
            BehaviorLog.employee_id == investigation.employee_id
        )
        .first()
    )

    if not log:
        return {"events": []}

    events = []

    # Employee Login
    events.append({
        "time": f"{log.login_hour:02d}:00",
        "title": "Employee Login",
        "description": "Employee logged into the corporate system.",
        "severity": "Informational",
        "icon": "login"
    })

    # Failed Login Attempts
    if log.failed_logins > 0:

        events.append({
            "time": f"{log.login_hour:02d}:10",
            "title": "Failed Login Attempts",
            "description": f"{log.failed_logins} failed login attempts detected.",
            "severity": "Medium" if log.failed_logins < 8 else "High",
            "icon": "failed_login"
        })

    # USB Usage
    if log.usb_used:

        events.append({
            "time": f"{log.login_hour:02d}:20",
            "title": "USB Device Connected",
            "description": "External USB device usage detected.",
            "severity": "High",
            "icon": "usb"
        })

    # File Downloads
    if log.files_downloaded > 0:

        events.append({
            "time": f"{log.login_hour:02d}:30",
            "title": "File Downloads",
            "description": f"{log.files_downloaded} files downloaded.",
            "severity": "High" if log.files_downloaded >= 400 else "Medium",
            "icon": "download"
        })

    # Emails Sent
    if log.emails_sent > 0:

        events.append({
            "time": f"{log.login_hour:02d}:40",
            "title": "Email Activity",
            "description": f"{log.emails_sent} emails sent.",
            "severity": "High" if log.emails_sent >= 80 else "Low",
            "icon": "email"
        })

    # After Hours Login
    if log.after_hours_login:

        events.append({
            "time": "22:00",
            "title": "After Hours Activity",
            "description": "Employee accessed the system outside business hours.",
            "severity": "High",
            "icon": "clock"
        })

    # AI Detection
    events.append({
        "time": "22:05",
        "title": "AI Threat Detection",
        "description": "UEBA Intelligence Engine detected suspicious behaviour.",
        "severity": investigation.threat_severity,
        "icon": "ai"
    })

    # Investigation Created
    events.append({
        "time": "22:06",
        "title": "Threat Investigation Created",
        "description": "Automatic investigation created by AI Threat Detection Engine.",
        "severity": investigation.threat_severity,
        "icon": "investigation"
    })

    return {
        "events": events
    }

# =====================================================
# Threat Evidence Collection
# =====================================================

def get_threat_evidence(
    db: Session,
    investigation_id: int
):
    """
    Return all evidence that triggered
    the threat investigation.
    """

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    log = (
        db.query(BehaviorLog)
        .filter(
            BehaviorLog.employee_id == investigation.employee_id
        )
        .first()
    )

    if not log:
        return None

    # Determine Detection Method
    if investigation.threat_severity in [
        "High",
        "Critical"
    ]:
        detection_method = "Hybrid Rule Engine"

    else:
        detection_method = "Isolation Forest"

    return {

        "failed_logins": log.failed_logins,

        "files_downloaded": log.files_downloaded,

        "emails_sent": log.emails_sent,

        "usb_used": log.usb_used,

        "after_hours_login": log.after_hours_login,

        "risk_level": investigation.threat_severity,

        "detection_method": detection_method

    }

# =====================================================
# Device Analysis
# =====================================================

def get_device_analysis(
    db: Session,
    investigation_id: int
):
    """
    Return device usage analysis for
    an investigation.
    """

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    log = (
        db.query(BehaviorLog)
        .filter(
            BehaviorLog.employee_id == investigation.employee_id
        )
        .first()
    )

    if not log:
        return None

    # Calculate Device Risk
    if (
        log.usb_used
        and log.after_hours_login
        and log.files_downloaded >= 400
    ):

        device_risk = "High"

    elif (
        log.usb_used
        or log.after_hours_login
    ):

        device_risk = "Medium"

    else:

        device_risk = "Low"

    return {

        "login_hour": log.login_hour,

        "usb_used": log.usb_used,

        "after_hours_login": log.after_hours_login,

        "files_downloaded": log.files_downloaded,

        "emails_sent": log.emails_sent,

        "device_risk": device_risk

    }

# =====================================================
# User Risk History
# =====================================================

def get_user_risk_history(
    db: Session,
    investigation_id: int
):
    """
    Return historical risk profile for
    an investigated employee.
    """

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    employee = (
        db.query(Employee)
        .filter(
            Employee.id == investigation.employee_id
        )
        .first()
    )

    if not employee:
        return None

    investigations = (
        db.query(Investigation)
        .filter(
            Investigation.employee_id == employee.id
        )
        .all()
    )

    total_incidents = len(investigations)

    current_risk = investigation.threat_severity

    if total_incidents > 1:
        previous_risk = investigations[-2].threat_severity
    else:
        previous_risk = "None"

    # Approximate score from severity
    score_map = {
        "Low": 25,
        "Medium": 50,
        "High": 75,
        "Critical": 100
    }

    scores = [
        score_map.get(i.threat_severity, 25)
        for i in investigations
    ]

    average_risk_score = (
        int(sum(scores) / len(scores))
        if scores else 0
    )

    # Behaviour trend
    if current_risk == "Critical":
        trend = "Increasing"

    elif current_risk == "High":
        trend = "Elevated"

    else:
        trend = "Stable"

    return {

        "employee_name": employee.full_name,

        "current_risk": current_risk,

        "previous_risk": previous_risk,

        "total_incidents": total_incidents,

        "average_risk_score": average_risk_score,

        "behaviour_trend": trend

    }

# =====================================================
# Event Correlation
# =====================================================

def get_event_correlation(
    db: Session,
    investigation_id: int
):
    """
    Correlate suspicious behaviour events
    for an investigation.
    """

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    employee = (
        db.query(Employee)
        .filter(
            Employee.id == investigation.employee_id
        )
        .first()
    )

    log = (
        db.query(BehaviorLog)
        .filter(
            BehaviorLog.employee_id == employee.id
        )
        .order_by(
            BehaviorLog.created_at.desc()
        )
        .first()
    )

    if not log:
        return None

    events = []

    score = 0

    if log.failed_logins >= 5:

        events.append({
            "event": "Multiple Failed Login Attempts",
            "severity": "High",
            "correlated": True
        })

        score += 20

    if log.usb_used:

        events.append({
            "event": "USB Device Connected",
            "severity": "High",
            "correlated": True
        })

        score += 20

    if log.files_downloaded >= 100:

        events.append({
            "event": "Mass File Download",
            "severity": "High",
            "correlated": True
        })

        score += 20

    if log.emails_sent >= 50:

        events.append({
            "event": "Bulk Email Activity",
            "severity": "Medium",
            "correlated": True
        })

        score += 20

    if log.after_hours_login:

        events.append({
            "event": "After Hours Login",
            "severity": "High",
            "correlated": True
        })

        score += 20

    return {

        "employee_name": employee.full_name,

        "total_events": len(events),

        "risk_level": investigation.threat_severity,

        "correlation_score": score,

        "events": events

    }

# =====================================================
# Investigation Workflow
# =====================================================

def update_investigation_workflow(
    db: Session,
    investigation_id: int,
    workflow
):
    """
    Update investigation workflow.
    """

    investigation = (
        db.query(Investigation)
        .filter(
            Investigation.id == investigation_id
        )
        .first()
    )

    if not investigation:
        return None

    investigation.assigned_analyst = workflow.assigned_analyst

    investigation.status = workflow.status

    investigation.investigation_notes = workflow.investigation_notes

    investigation.recommendation = workflow.recommendation

    db.commit()

    db.refresh(investigation)

    return {

        "message": "Investigation updated successfully",

        "investigation_id": investigation.id,

        "assigned_analyst": investigation.assigned_analyst,

        "status": investigation.status

    }