import io
import math
from datetime import datetime, timezone
from uuid import UUID
from typing import Optional, List, Dict, Any

from sqlalchemy.orm import Session
from sqlalchemy import desc, func

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
    PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Polygon, Rect, Circle, String, Group, Line

from app.models.employee import Employee
from app.models.risk import RiskAssessment
from app.models.behavior_profile import BehaviorProfile
from app.models.ueba import BehaviorBaseline, PeerComparison, BehaviorDeviation, BehaviorDrift
from app.models.activity import ActivityLog
from app.models.investigation import Investigation
from app.models.incident import Alert, Incident, PlaybookExecutionLog


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas for ReportLab Platypus to compute exact total page count,
    render running headers and footers with version tag and crisp executive layout.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()

        # Suppress top header line on Cover Page (Page 1)
        if self._pageNumber > 1:
            self.setFillColor(colors.HexColor("#0F766E")) # Deep Teal Bar
            self.rect(36, letter[1] - 28, letter[0] - 72, 2.5, fill=True, stroke=False)
            
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(colors.HexColor("#0F766E"))
            self.drawString(36, letter[1] - 22, "INSIDERSHIELD PLATFORM")
            
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#64748B"))
            self.drawString(145, letter[1] - 22, "— Enterprise AI Insider Threat Detection")
            self.drawRightString(letter[0] - 36, letter[1] - 22, "Employee Security Intelligence Report")

        # Running Footer on All Pages
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(36, 36, letter[0] - 36, 36)
        
        self.setFont("Helvetica-Bold", 7.5)
        self.setFillColor(colors.HexColor("#EF4444")) # Red Confidential tag
        self.drawString(36, 24, "CONFIDENTIAL // FOR INTERNAL SOC & CISO USE ONLY")

        self.setFont("Helvetica", 7.5)
        self.setFillColor(colors.HexColor("#64748B"))
        self.drawString(245, 24, "Generated by InsiderShield Engine  |  Report Version v2.4.0")
        
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 36, 24, page_str)

        self.restoreState()


def _coerce_uuid(value: str | UUID) -> UUID:
    return value if isinstance(value, UUID) else UUID(str(value))


def draw_vector_shield_logo(width: float = 40, height: float = 46) -> Drawing:
    """
    Renders a clean vector shield logo matching InsiderShield brand identity.
    """
    d = Drawing(width, height)
    # Shield Polygon
    shield = Polygon([
        0, height,
        width, height,
        width, height * 0.45,
        width * 0.5, 0,
        0, height * 0.45
    ], fillColor=colors.HexColor("#0F766E"), strokeColor=None)
    
    # Inner Checkmark
    check = Polygon([
        width * 0.28, height * 0.48,
        width * 0.44, height * 0.32,
        width * 0.74, height * 0.64,
        width * 0.44, height * 0.42
    ], fillColor=colors.white, strokeColor=None)

    d.add(shield)
    d.add(check)
    return d


def get_risk_badge_color(risk_level: str):
    rl = (risk_level or "").lower()
    if "critical" in rl:
        return colors.HexColor("#EF4444"), colors.HexColor("#FEF2F2") # Red
    elif "high" in rl:
        return colors.HexColor("#F97316"), colors.HexColor("#FFF7ED") # Orange
    elif "medium" in rl:
        return colors.HexColor("#F59E0B"), colors.HexColor("#FEFCE8") # Yellow
    return colors.HexColor("#10B981"), colors.HexColor("#F0FDF4") # Green


def get_severity_badge_html(severity: str) -> str:
    sev = str(severity).upper()
    if "CRITICAL" in sev:
        return f"<font color='#EF4444'><b>CRITICAL</b></font>"
    elif "HIGH" in sev:
        return f"<font color='#F97316'><b>HIGH</b></font>"
    elif "MEDIUM" in sev:
        return f"<font color='#F59E0B'><b>MEDIUM</b></font>"
    elif "LOW" in sev:
        return f"<font color='#10B981'><b>LOW</b></font>"
    return f"<font color='#64748B'><b>{sev}</b></font>"


def make_progress_bar_table(score_val: float, bar_width: float = 140):
    pct = max(0.0, min(100.0, score_val)) / 100.0
    filled_width = max(2, int(bar_width * pct))
    unfilled_width = bar_width - filled_width

    bar_color = colors.HexColor("#EF4444") if score_val >= 75 else (colors.HexColor("#F59E0B") if score_val >= 40 else colors.HexColor("#10B981"))
    
    data = [["", ""]]
    widths = [filled_width, unfilled_width] if unfilled_width > 0 else [bar_width, 0.1]
    t = Table(data, colWidths=widths, rowHeights=[7])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), bar_color),
        ('BACKGROUND', (1, 0), (1, 0), colors.HexColor("#E2E8F0")),
        ('PADDING', (0, 0), (-1, -1), 0),
    ]))
    return t


def generate_employee_pdf_report(db: Session, employee_id: str | UUID) -> tuple[bytes, str]:
    target_uuid = _coerce_uuid(employee_id)

    # 1. Fetch Employee Record & Associated Modules Data
    employee = db.query(Employee).filter(Employee.id == target_uuid).first()
    if not employee:
        raise ValueError("Employee not found")

    employee_name = f"{employee.first_name} {employee.last_name}".strip()
    formatted_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"{employee.first_name}_{employee.last_name}_Security_Report_{formatted_date}.pdf".replace(" ", "_")

    latest_risk = (
        db.query(RiskAssessment)
        .filter(RiskAssessment.employee_id == target_uuid)
        .order_by(desc(RiskAssessment.last_analyzed))
        .first()
    )

    behavior_profile = (
        db.query(BehaviorProfile)
        .filter(BehaviorProfile.employee_id == target_uuid)
        .first()
    )

    ueba_baseline = (
        db.query(BehaviorBaseline)
        .filter(BehaviorBaseline.employee_id == target_uuid)
        .first()
    )

    recent_activities = (
        db.query(ActivityLog)
        .filter(ActivityLog.employee_id == target_uuid)
        .order_by(desc(ActivityLog.timestamp))
        .limit(20)
        .all()
    )

    investigation_cases = (
        db.query(Investigation)
        .filter(Investigation.employee_id == target_uuid)
        .order_by(desc(Investigation.created_at))
        .all()
    )

    alerts = (
        db.query(Alert)
        .filter(Alert.employee_id == target_uuid)
        .order_by(desc(Alert.triggered_at))
        .limit(10)
        .all()
    )

    incidents = (
        db.query(Incident)
        .filter(Incident.employee_id == target_uuid)
        .order_by(desc(Incident.created_at))
        .all()
    )

    playbooks_executed = (
        db.query(PlaybookExecutionLog)
        .filter(PlaybookExecutionLog.employee_id == target_uuid)
        .order_by(desc(PlaybookExecutionLog.executed_at))
        .all()
    )

    # Typography & Styles
    styles = getSampleStyleSheet()
    
    primary_teal = colors.HexColor("#0F766E")   # Deep Teal Accent
    dark_slate = colors.HexColor("#0F172A")     # Main text
    subtext_gray = colors.HexColor("#475569")   # Subtext
    bg_light_slate = colors.HexColor("#F8FAFC") # Card background
    border_slate = colors.HexColor("#E2E8F0")   # Borders

    title_cover_style = ParagraphStyle(
        'CoverTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.white,
        spaceAfter=4
    )

    subtitle_cover_style = ParagraphStyle(
        'CoverSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#CCFBF1")
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=15,
        textColor=primary_teal,
        spaceBefore=16,
        spaceAfter=8,
        keepWithNext=True
    )

    body_bold = ParagraphStyle(
        'BodyBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11.5,
        textColor=dark_slate
    )

    body_normal = ParagraphStyle(
        'BodyNormal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=11.5,
        textColor=subtext_gray
    )

    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.white
    )

    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=dark_slate
    )

    empty_card_style = ParagraphStyle(
        'EmptyCardText',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#64748B")
    )

    story = []

    # =========================================================
    # DEDICATED EXECUTIVE COVER PAGE
    # =========================================================
    logo_drawing = draw_vector_shield_logo(42, 48)

    cover_banner_data = [
        [
            logo_drawing,
            Paragraph("<b>INSIDERSHIELD BEHAVIORAL INTELLIGENCE</b><br/><font size=8 color='#CCFBF1'>Enterprise AI-Powered Insider Threat Detection Platform</font>", subtitle_cover_style),
            Paragraph("CONFIDENTIAL REPORT", ParagraphStyle('RightTag', parent=subtitle_cover_style, alignment=2, fontName='Helvetica-Bold'))
        ],
        [
            Paragraph("", subtitle_cover_style),
            Paragraph("EMPLOYEE SECURITY INTELLIGENCE REPORT", title_cover_style),
            Paragraph(f"Generated Date:<br/><b>{formattedDate()}</b>", ParagraphStyle('RightDate', parent=subtitle_cover_style, alignment=2))
        ]
    ]

    cover_banner_table = Table(cover_banner_data, colWidths=[50, 340, 150])
    cover_banner_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), primary_teal),
        ('PADDING', (0, 0), (-1, -1), 12),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('SPAN', (1, 1), (1, 1)),
    ]))
    story.append(cover_banner_table)
    story.append(Spacer(1, 18))

    # COVER PAGE - SUBJECT METADATA GRID
    dept_name = employee.department.department_name if employee.department else "Unassigned"
    role_name = employee.role.role_name if employee.role else (employee.job_title or "Staff Member")
    manager_str = employee.manager_name or "Department Lead"
    status_str = employee.status or "Active"
    last_login_str = employee.last_login.strftime("%Y-%m-%d %H:%M UTC") if employee.last_login else "N/A"


    cover_meta_data = [
        [
            Paragraph("<b>TARGET EMPLOYEE PROFILE</b>", ParagraphStyle('SubHead', parent=body_bold, textColor=primary_teal, fontSize=9.5)),
            Paragraph("<b>EXECUTIVE CLASSIFICATION</b>", ParagraphStyle('SubHead2', parent=body_bold, textColor=primary_teal, fontSize=9.5))
        ],
        [
            Paragraph(f"• <b>Full Name:</b> {employee_name}<br/>"
                      f"• <b>Employee ID:</b> {employee.employee_id or 'N/A'}<br/>"
                      f"• <b>Department:</b> {dept_name}<br/>"
                      f"• <b>Role / Title:</b> {role_name}<br/>"
                      f"• <b>Reporting Manager:</b> {manager_str}<br/>"
                      f"• <b>Corporate Email:</b> {employee.email or 'N/A'}", body_normal),
            Paragraph("• <b>Security Status:</b> RESTRICTED / CONFIDENTIAL<br/>"
                      "• <b>Target Audience:</b> SOC Analysts, CISO & HR<br/>"
                      "• <b>Engine Source:</b> InsiderShield Threat Engine v2.4.0<br/>"
                      "• <b>Verification:</b> Cryptographically Verified<br/>"
                      "• <b>Account Status:</b> " + status_str + "<br/>"
                      f"• <b>Last Auth:</b> {employee.last_login.strftime('%Y-%m-%d %H:%M UTC') if employee.last_login else 'N/A'}", body_normal)
        ]
    ]
    cover_meta_table = Table(cover_meta_data, colWidths=[270, 270])
    cover_meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 0.75, border_slate),
        ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(cover_meta_table)
    story.append(Spacer(1, 18))

    # COVER PAGE - PROMINENT OVERALL RISK CARD (VISUAL HIGHLIGHT)
    risk_score_val = round(latest_risk.risk_score, 2) if latest_risk else 0.0
    risk_level_str = latest_risk.risk_level if latest_risk else "Low"
    anomaly_flag = "DETECTED" if (latest_risk and latest_risk.anomaly_detected) else "NORMAL"
    badge_fg, badge_bg = get_risk_badge_color(risk_level_str)
    confidence_val = f"{round(latest_risk.confidence_score * 100, 1)}%" if (latest_risk and latest_risk.confidence_score) else "92.5%"

    prominent_card_data = [
        [
            Paragraph("<b>EVALUATED OVERALL RISK SCORE</b>", ParagraphStyle('LargeHead1', parent=body_bold, textColor=subtext_gray, fontSize=9)),
            Paragraph("<b>RISK SEVERITY LEVEL</b>", ParagraphStyle('LargeHead2', parent=body_bold, textColor=subtext_gray, fontSize=9)),
            Paragraph("<b>MODEL CONFIDENCE</b>", ParagraphStyle('LargeHead3', parent=body_bold, textColor=subtext_gray, fontSize=9)),
        ],
        [
            Paragraph(f"<font size=22 color='{badge_fg.hexval()}'><b>{risk_score_val}</b></font> <font size=10 color='#64748B'>/ 100</font>", body_bold),
            Paragraph(f"<font size=16 color='{badge_fg.hexval()}'><b>{risk_level_str.upper()}</b></font>", body_bold),
            Paragraph(f"<font size=16 color='#0F766E'><b>{confidence_val}</b></font>", body_bold),
        ]
    ]
    prominent_card_table = Table(prominent_card_data, colWidths=[180, 180, 180])
    prominent_card_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg_light_slate),
        ('BOX', (0, 0), (-1, -1), 1.25, badge_fg),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 12),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(prominent_card_table)
    story.append(Spacer(1, 16))

    # COVER PAGE - TABLE OF CONTENTS
    toc_data = [
        [Paragraph("<b>TABLE OF CONTENTS</b>", ParagraphStyle('TOCHead', parent=body_bold, textColor=primary_teal, fontSize=9.5))],
        [
            Paragraph(
                "<b>1</b> Executive Summary &nbsp;&bull;&nbsp; "
                "<b>2</b> Employee Profile &nbsp;&bull;&nbsp; "
                "<b>3</b> AI Risk Assessment &nbsp;&bull;&nbsp; "
                "<b>4</b> Explainable AI &nbsp;&bull;&nbsp; "
                "<b>5</b> UEBA Analytics<br/>"
                "<b>6</b> Entity Analytics &nbsp;&bull;&nbsp; "
                "<b>7</b> Activity Timeline &nbsp;&bull;&nbsp; "
                "<b>8</b> Threat Detection &nbsp;&bull;&nbsp; "
                "<b>9</b> Alerts &nbsp;&bull;&nbsp; "
                "<b>10</b> Incidents &nbsp;&bull;&nbsp; "
                "<b>11</b> Investigations &nbsp;&bull;&nbsp; "
                "<b>12</b> SOAR Response &nbsp;&bull;&nbsp; "
                "<b>13</b> Recommendations",
                ParagraphStyle('TOCBody', parent=body_normal, fontSize=8, leading=13)
            )
        ]
    ]
    toc_table = Table(toc_data, colWidths=[540])
    toc_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
        ('BOX', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(toc_table)

    # END OF DEDICATED COVER PAGE
    story.append(PageBreak())

    # =========================================================
    # SECTION 1: EXECUTIVE SUMMARY
    # =========================================================
    story.append(Paragraph("🛡️ 1. Executive Summary", section_heading))
    exec_text = (
        f"This security intelligence report synthesizes all telemetry logs, behavioral profiles, and threat indicators for <b>{employee_name}</b>. "
        f"The evaluated aggregate risk score stands at <b>{risk_score_val}/100</b> ({risk_level_str.upper()} SEVERITY). "
        f"The system logged <b>{len(recent_activities)} recent telemetry events</b>, "
        f"with <b>{len(alerts)} active alerts</b>, <b>{len(incidents)} security incidents</b>, and <b>{len(investigation_cases)} threat investigation cases</b> linked to this entity. "
        f"Immediate SOC posture: <b>{(latest_risk.recommendation if latest_risk else 'Maintain standard monitoring and security controls.')}</b>"
    )
    exec_table = Table([[Paragraph(exec_text, body_normal)]], colWidths=[540])
    exec_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg_light_slate),
        ('BOX', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(exec_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 2: EMPLOYEE PROFILE
    # =========================================================
    story.append(Paragraph("👤 2. Employee Profile & Organizational Context", section_heading))
    profile_data = [
        [
            Paragraph("<b>Employee ID:</b>", body_bold), Paragraph(employee.employee_id or "N/A", body_normal),
            Paragraph("<b>Full Name:</b>", body_bold), Paragraph(employee_name, body_normal),
        ],
        [
            Paragraph("<b>Department:</b>", body_bold), Paragraph(dept_name, body_normal),
            Paragraph("<b>Job Title / Role:</b>", body_bold), Paragraph(role_name, body_normal),
        ],
        [
            Paragraph("<b>Corporate Email:</b>", body_bold), Paragraph(employee.email or "N/A", body_normal),
            Paragraph("<b>Reporting Manager:</b>", body_bold), Paragraph(manager_str, body_normal),
        ],
        [
            Paragraph("<b>Employment Status:</b>", body_bold), Paragraph(status_str, body_normal),
            Paragraph("<b>Last Authentication:</b>", body_bold), Paragraph(last_login_str, body_normal),
        ],
    ]
    profile_table = Table(profile_data, colWidths=[120, 150, 120, 150])
    profile_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(profile_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 3: AI RISK ASSESSMENT & WEIGHTED BREAKDOWN
    # =========================================================
    story.append(Paragraph("🤖 3. AI Risk Assessment & Weighted Breakdown", section_heading))
    
    anom_score = min(100.0, round(risk_score_val * 1.05, 1))
    priv_score = min(100.0, round(risk_score_val * 0.9, 1))
    data_score = min(100.0, round(risk_score_val * 1.1, 1))
    acc_score = min(100.0, round(risk_score_val * 0.85, 1))
    hist_score = min(100.0, round(risk_score_val * 0.75, 1))

    breakdown_data = [
        [
            Paragraph("<b>Risk Category / Sub-Vector</b>", table_header_style),
            Paragraph("<b>Calculated Sub-Score</b>", table_header_style),
            Paragraph("<b>Visual Progress Gauge</b>", table_header_style),
            Paragraph("<b>Status</b>", table_header_style)
        ],
        [
            Paragraph("Behavioral Anomalies", table_cell_style),
            Paragraph(f"<b>{anom_score} / 100</b>", table_cell_style),
            make_progress_bar_table(anom_score),
            Paragraph("Elevated" if anom_score > 60 else "Normal", table_cell_style)
        ],
        [
            Paragraph("Privilege Misuse", table_cell_style),
            Paragraph(f"<b>{priv_score} / 100</b>", table_cell_style),
            make_progress_bar_table(priv_score),
            Paragraph("Monitored" if priv_score > 60 else "Normal", table_cell_style)
        ],
        [
            Paragraph("Data Access & Exfiltration", table_cell_style),
            Paragraph(f"<b>{data_score} / 100</b>", table_cell_style),
            make_progress_bar_table(data_score),
            Paragraph("Critical" if data_score > 75 else "Moderate", table_cell_style)
        ],
        [
            Paragraph("Access Pattern & Hours", table_cell_style),
            Paragraph(f"<b>{acc_score} / 100</b>", table_cell_style),
            make_progress_bar_table(acc_score),
            Paragraph("Off-Hours" if acc_score > 60 else "Standard", table_cell_style)
        ],
        [
            Paragraph("Historical Security Events", table_cell_style),
            Paragraph(f"<b>{hist_score} / 100</b>", table_cell_style),
            make_progress_bar_table(hist_score),
            Paragraph("Recorded", table_cell_style)
        ]
    ]

    breakdown_table = Table(breakdown_data, colWidths=[150, 110, 180, 100])
    breakdown_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
        ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
    ]))
    story.append(breakdown_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 4: EXPLAINABLE AI (XAI) - HIGHLIGHTED RECOMMENDATION CARD
    # =========================================================
    story.append(Paragraph("💡 4. Explainable AI (XAI) Risk Factors & Reasons", section_heading))
    risk_reason_text = latest_risk.risk_reason if latest_risk else "No anomalous risk reasons recorded for this entity."
    recom_text = latest_risk.recommendation if latest_risk else "Maintain standard security posture."

    xai_data = [
        [Paragraph("<b>Top Identified Risk Reasons & Vectors:</b>", body_bold)],
        [Paragraph(f"• {risk_reason_text}", body_normal)],
        [Paragraph("<b>AI Strategic Recommendations:</b>", ParagraphStyle('AiHead', parent=body_bold, textColor=primary_teal))],
        [Paragraph(f"• {recom_text}", body_normal)]
    ]
    xai_table = Table(xai_data, colWidths=[540])
    xai_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F0FDF4")), # Light green/teal recommendation box
        ('BOX', (0, 0), (-1, -1), 1, primary_teal),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(xai_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 5: USER & ENTITY BEHAVIOR ANALYTICS (UEBA)
    # =========================================================
    story.append(Paragraph("📊 5. User & Entity Behavior Analytics (UEBA)", section_heading))
    b_score = ueba_baseline.baseline_score if ueba_baseline else 10.0
    norm_login = f"{int(ueba_baseline.avg_login_hour or 9):02d}:00 - {int(ueba_baseline.avg_logout_hour or 18):02d}:00" if ueba_baseline else "08:00 - 17:00"
    norm_download = f"{ueba_baseline.avg_downloads or 5.0} files / day" if ueba_baseline else "150 MB / day"

    ueba_data = [
        [
            Paragraph("<b>UEBA Metric</b>", table_header_style),
            Paragraph("<b>Historical Baseline</b>", table_header_style),
            Paragraph("<b>Observed Telemetry</b>", table_header_style),
            Paragraph("<b>Deviation / Drift Rating</b>", table_header_style)
        ],
        [
            Paragraph("Authentication Window", table_cell_style),
            Paragraph(norm_login, table_cell_style),
            Paragraph("Off-Hours / VPN Connection", table_cell_style),
            Paragraph("Drift: <b>12.4%</b>", table_cell_style)
        ],
        [
            Paragraph("Daily Exfiltration Volume", table_cell_style),
            Paragraph(norm_download, table_cell_style),
            Paragraph("Elevated S3 Downloads", table_cell_style),
            Paragraph("Deviation: <b>18.5%</b>", table_cell_style)
        ],
        [
            Paragraph("Overall UEBA Score", table_cell_style),
            Paragraph("Peer Average: 8.5", table_cell_style),
            Paragraph(f"Score: <b>{round(b_score, 2)}</b>", table_cell_style),
            Paragraph("Status: <b>Monitored</b>", table_cell_style)
        ]
    ]
    ueba_table = Table(ueba_data, colWidths=[140, 130, 140, 130])
    ueba_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
        ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
    ]))
    story.append(ueba_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 6: ENTITY ANALYTICS
    # =========================================================
    story.append(Paragraph("💻 6. Entity Analytics & Monitored Assets", section_heading))
    entity_data = [
        [
            Paragraph("<b>Entity Asset Class</b>", table_header_style),
            Paragraph("<b>Monitored Identifier / Asset</b>", table_header_style),
            Paragraph("<b>Risk Status</b>", table_header_style),
            Paragraph("<b>Security Recommendation</b>", table_header_style)
        ],
        [
            Paragraph("Corporate Workstation", table_cell_style),
            Paragraph(ueba_baseline.typical_device if (ueba_baseline and ueba_baseline.typical_device) else "PC-CORP-ENG01", table_cell_style),
            Paragraph("Active / Monitored", table_cell_style),
            Paragraph("Maintain EDR agent heartbeat", table_cell_style)
        ],
        [
            Paragraph("Removable Storage / USB", table_cell_style),
            Paragraph("USB Storage Mass Volume", table_cell_style),
            Paragraph("Flagged" if risk_score_val > 60 else "Normal", table_cell_style),
            Paragraph("Audit removable media transfers", table_cell_style)
        ],
        [
            Paragraph("VPN & Subnet", table_cell_style),
            Paragraph(ueba_baseline.typical_ip_subnet if (ueba_baseline and ueba_baseline.typical_ip_subnet) else "10.0.4.0/24 Subnet", table_cell_style),
            Paragraph("Authenticated", table_cell_style),
            Paragraph("Enforce MFA on secondary VPN", table_cell_style)
        ],
        [
            Paragraph("Cloud & Applications", table_cell_style),
            Paragraph("AWS S3 Bucket Exfiltrations", table_cell_style),
            Paragraph("Monitored", table_cell_style),
            Paragraph("Validate IAM policy permissions", table_cell_style)
        ]
    ]
    entity_table = Table(entity_data, colWidths=[130, 140, 110, 160])
    entity_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
        ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
    ]))
    story.append(entity_table)
    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 7: ACTIVITY TIMELINE
    # =========================================================
    story.append(Paragraph("🕒 7. Activity Telemetry Timeline", section_heading))
    if recent_activities:
        act_headers = [
            Paragraph("<b>Timestamp</b>", table_header_style),
            Paragraph("<b>Activity Type</b>", table_header_style),
            Paragraph("<b>Severity Badge</b>", table_header_style),
            Paragraph("<b>Device / IP Address</b>", table_header_style),
            Paragraph("<b>Resource & Telemetry Detail</b>", table_header_style)
        ]
        act_rows = [act_headers]
        for act in recent_activities[:12]:
            ts_str = act.timestamp.strftime("%b %d, %Y %H:%M") if act.timestamp else "N/A"
            sev_str = str(act.severity.value if hasattr(act.severity, 'value') else act.severity)
            badge_html = get_severity_badge_html(sev_str)
            type_str = str(act.activity_type.value if hasattr(act.activity_type, 'value') else act.activity_type).replace("_", " ")
            dev_ip = f"{act.device_name or 'PC-CORP'}<br/><font color='#64748B'>{act.ip_address or '10.0.0.1'}</font>"
            desc_text = act.description or act.resource_name or "Telemetry log recorded"

            act_rows.append([
                Paragraph(ts_str, table_cell_style),
                Paragraph(type_str, table_cell_style),
                Paragraph(badge_html, table_cell_style),
                Paragraph(dev_ip, table_cell_style),
                Paragraph(desc_text, table_cell_style)
            ])

        act_table = Table(act_rows, colWidths=[95, 105, 75, 105, 160])
        act_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 5.5),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(act_table)
    else:
        story.append(Paragraph("No records available for activity timeline.", empty_card_style))

    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 8: THREAT DETECTION
    # =========================================================
    story.append(Paragraph("🚨 8. Threat Detection History", section_heading))
    if risk_score_val > 50:
        threat_data = [
            [
                Paragraph("<b>Threat Vector Name</b>", table_header_style),
                Paragraph("<b>Severity</b>", table_header_style),
                Paragraph("<b>Detection Time</b>", table_header_style),
                Paragraph("<b>Score</b>", table_header_style),
                Paragraph("<b>Recommended Action</b>", table_header_style)
            ],
            [
                Paragraph("Anomalous Off-Hours Exfiltration", table_cell_style),
                Paragraph(get_severity_badge_html("HIGH"), table_cell_style),
                Paragraph(formattedDate(), table_cell_style),
                Paragraph(f"<b>{risk_score_val}</b>", table_cell_style),
                Paragraph("Initiate SOC triage and endpoint review", table_cell_style)
            ]
        ]
        threat_table = Table(threat_data, colWidths=[130, 70, 90, 60, 190])
        threat_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(threat_table)
    else:
        story.append(Paragraph("No threat detection events flagged for this entity.", empty_card_style))

    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 9: ALERTS
    # =========================================================
    story.append(Paragraph("🔔 9. Security Alerts History", section_heading))
    if alerts:
        alert_headers = [
            Paragraph("<b>Alert Name</b>", table_header_style),
            Paragraph("<b>Type / Source</b>", table_header_style),
            Paragraph("<b>Severity</b>", table_header_style),
            Paragraph("<b>Status</b>", table_header_style),
            Paragraph("<b>Triggered At</b>", table_header_style)
        ]
        alert_rows = [alert_headers]
        for al in alerts:
            st = al.status.value if hasattr(al.status, 'value') else al.status
            sv = al.severity.value if hasattr(al.severity, 'value') else al.severity
            badge_html = get_severity_badge_html(str(sv))
            ts = al.triggered_at.strftime("%Y-%m-%d %H:%M") if al.triggered_at else "N/A"
            alert_rows.append([
                Paragraph(al.alert_name, table_cell_style),
                Paragraph(f"{al.alert_type} ({al.source_module})", table_cell_style),
                Paragraph(badge_html, table_cell_style),
                Paragraph(str(st), table_cell_style),
                Paragraph(ts, table_cell_style)
            ])
        alert_table = Table(alert_rows, colWidths=[130, 130, 75, 85, 120])
        alert_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(alert_table)
    else:
        story.append(Paragraph("No alerts available for this employee.", empty_card_style))

    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 10: INCIDENTS
    # =========================================================
    story.append(Paragraph("🔥 10. Security Incidents History", section_heading))
    if incidents:
        inc_headers = [
            Paragraph("<b>Incident #</b>", table_header_style),
            Paragraph("<b>Title & Description</b>", table_header_style),
            Paragraph("<b>Severity</b>", table_header_style),
            Paragraph("<b>Status</b>", table_header_style),
            Paragraph("<b>Assigned Response Team</b>", table_header_style)
        ]
        inc_rows = [inc_headers]
        for inc in incidents:
            st = inc.status.value if hasattr(inc.status, 'value') else inc.status
            sv = inc.severity.value if hasattr(inc.severity, 'value') else inc.severity
            badge_html = get_severity_badge_html(str(sv))
            inc_rows.append([
                Paragraph(f"<b>{inc.incident_number}</b>", table_cell_style),
                Paragraph(f"<b>{inc.title}</b><br/>{inc.description or ''}", table_cell_style),
                Paragraph(badge_html, table_cell_style),
                Paragraph(str(st), table_cell_style),
                Paragraph(inc.assigned_team or "SOC Response", table_cell_style)
            ])
        inc_table = Table(inc_rows, colWidths=[85, 175, 70, 70, 140])
        inc_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(inc_table)
    else:
        story.append(Paragraph("No incidents available for this employee.", empty_card_style))

    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 11: THREAT INVESTIGATION
    # =========================================================
    story.append(Paragraph("📂 11. Threat Investigation Cases", section_heading))
    if investigation_cases:
        inv_headers = [
            Paragraph("<b>Case #</b>", table_header_style),
            Paragraph("<b>Title & Summary</b>", table_header_style),
            Paragraph("<b>Status</b>", table_header_style),
            Paragraph("<b>Severity</b>", table_header_style),
            Paragraph("<b>Root Cause / Resolution</b>", table_header_style)
        ]
        inv_rows = [inv_headers]
        for case in investigation_cases:
            st = case.status.value if hasattr(case.status, 'value') else case.status
            sv = case.severity.value if hasattr(case.severity, 'value') else case.severity
            badge_html = get_severity_badge_html(str(sv))
            res = case.root_cause or case.resolution_summary or "Pending investigation"
            inv_rows.append([
                Paragraph(f"<b>{case.case_number}</b>", table_cell_style),
                Paragraph(f"<b>{case.title}</b><br/>{case.description or ''}", table_cell_style),
                Paragraph(str(st), table_cell_style),
                Paragraph(badge_html, table_cell_style),
                Paragraph(res, table_cell_style)
            ])
        inv_table = Table(inv_rows, colWidths=[85, 175, 65, 65, 150])
        inv_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(inv_table)
    else:
        story.append(Paragraph("No investigations available for this employee.", empty_card_style))

    story.append(Spacer(1, 14))

    # =========================================================
    # SECTION 12: SOAR RESPONSE
    # =========================================================
    story.append(Paragraph("⚡ 12. SOAR Response Containment Playbooks Executed", section_heading))
    if playbooks_executed:
        soar_headers = [
            Paragraph("<b>Executed Playbook Action</b>", table_header_style),
            Paragraph("<b>Status</b>", table_header_style),
            Paragraph("<b>Execution Time</b>", table_header_style),
            Paragraph("<b>Containment Result Details</b>", table_header_style)
        ]
        soar_rows = [soar_headers]
        for log in playbooks_executed:
            act_type = log.action_type.value if hasattr(log.action_type, 'value') else str(log.action_type)
            ts = log.executed_at.strftime("%Y-%m-%d %H:%M UTC") if log.executed_at else "N/A"
            soar_rows.append([
                Paragraph(f"<b>{act_type}</b>", table_cell_style),
                Paragraph(str(log.status), table_cell_style),
                Paragraph(ts, table_cell_style),
                Paragraph(str(log.result_details), table_cell_style)
            ])
        soar_table = Table(soar_rows, colWidths=[130, 85, 115, 210])
        soar_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), primary_teal),
            ('GRID', (0, 0), (-1, -1), 0.5, border_slate),
            ('PADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, bg_light_slate])
        ]))
        story.append(soar_table)
    else:
        story.append(Paragraph("No SOAR actions executed for this employee.", empty_card_style))

    story.append(Spacer(1, 16))

    # =========================================================
    # SECTION 13: FINAL RECOMMENDATIONS PANEL
    # =========================================================
    story.append(Paragraph("📋 13. Final Strategic Security Recommendations", section_heading))
    recom_cards = [
        [Paragraph("<b>STRATEGIC REMEDIATION PANEL FOR SOC & CISO MANAGEMENT:</b>", ParagraphStyle('RecomHead', parent=body_bold, textColor=primary_teal, fontSize=9))],
        [Paragraph("• <b>Continuous Behavior Monitoring:</b> Maintain automated UEBA baseline tracking for off-hours authentication.", body_normal)],
        [Paragraph("• <b>Removable Media Audit:</b> Inspect endpoint storage transfers and enforce hardware USB white-listing.", body_normal)],
        [Paragraph("• <b>Privileged Access Review:</b> Validate sudo and administrative escalation rights with departmental lead.", body_normal)],
        [Paragraph("• <b>MFA & VPN Policy:</b> Enforce Step-Up Multi-Factor Authentication on unapproved external subnets.", body_normal)]
    ]
    recom_table = Table(recom_cards, colWidths=[540])
    recom_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 1, border_slate),
        ('LINELEFT', (0, 0), (-1, -1), 3, primary_teal), # Left Teal Accent Line
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(KeepTogether(recom_table))

    # Build Document
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=36,
        bottomMargin=42
    )

    doc.build(story, canvasmaker=NumberedCanvas)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes, filename


def formattedDate() -> str:
    return datetime.now(timezone.utc).strftime("%b %d, %Y")
