import { useEffect, useMemo, useState } from "react";

import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function ActivityLogs() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);

  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState("All");

  const [sortOrder, setSortOrder] = useState("desc");

  const [currentPage, setCurrentPage] = useState(1);

  const rowsPerPage = 10;

  useEffect(() => {
    fetch("/risk_scores.csv")
      .then((res) => res.text())
      .then((text) => {
        const rows = text.trim().split("\n");

        const headers = rows[0].split(",");

        const data = rows.slice(1).map((row) => {
          const values = row.split(",");

          const obj = {};

          headers.forEach((header, index) => {
            obj[header] = values[index];
          });

          return obj;
        });

        setLogs(data);
        setLoading(false);
      })
      .catch((err) => {
        console.log(err);
        setLoading(false);
      });
  }, []);

  const getSeverity = (risk) => {
    switch (risk) {
      case "Critical":
        return "Critical";

      case "High":
        return "High";

      case "Medium":
        return "Medium";

      default:
        return "Low";
    }
  };

  const filteredLogs = useMemo(() => {
    let filtered = logs.filter((log) => {
      const matchesSearch = log.user
        .toLowerCase()
        .includes(search.toLowerCase());

      const matchesSeverity =
        severityFilter === "All" ||
        getSeverity(log.risk_level) === severityFilter;

      return matchesSearch && matchesSeverity;
    });

    filtered.sort((a, b) =>
      sortOrder === "desc"
        ? Number(b.risk_score) - Number(a.risk_score)
        : Number(a.risk_score) - Number(b.risk_score)
    );

    return filtered;
  }, [logs, search, severityFilter, sortOrder]);

  const totalPages = Math.ceil(
    filteredLogs.length / rowsPerPage
  );

  const currentLogs = filteredLogs.slice(
    (currentPage - 1) * rowsPerPage,
    currentPage * rowsPerPage
  );

  const badgeColor = (risk) => {
    switch (risk) {
      case "Critical":
        return "bg-purple-600";

      case "High":
        return "bg-red-500";

      case "Medium":
        return "bg-yellow-500";

      default:
        return "bg-green-500";
    }
  };
return (
  <div className="flex bg-slate-100 min-h-screen">
    <Sidebar />

    <div className="flex-1">
      <Navbar />

      <div className="p-8">

        <div className="mb-8">

          <h1 className="text-3xl font-bold">
            Activity Logs
          </h1>

          <p className="text-gray-500">
            Monitor employee activities generated by the ML Engine
          </p>

        </div>

        {/* Search + Filters */}

        <div className="bg-white rounded-2xl shadow p-5 mb-6 flex flex-wrap gap-4">

          <input
            type="text"
            placeholder="Search User ID..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setCurrentPage(1);
            }}
            className="border rounded-lg px-4 py-2 w-72"
          />

          <select
            value={severityFilter}
            onChange={(e) => {
              setSeverityFilter(e.target.value);
              setCurrentPage(1);
            }}
            className="border rounded-lg px-4 py-2"
          >
            <option>All</option>
            <option>Critical</option>
            <option>High</option>
            <option>Medium</option>
            <option>Low</option>
          </select>

          <button
            onClick={() =>
              setSortOrder(
                sortOrder === "desc" ? "asc" : "desc"
              )
            }
            className="bg-cyan-600 text-white px-5 rounded-lg"
          >
            Sort Risk
            {sortOrder === "desc" ? " ↓" : " ↑"}
          </button>

        </div>

        {/* Table */}

        <div className="bg-white rounded-2xl shadow p-6 overflow-x-auto">

          {loading ? (

            <p>Loading Activity Logs...</p>

          ) : (

            <table className="w-full">

              <thead>

                <tr className="border-b text-left">

                  <th className="pb-4">User</th>

                  <th>Risk Score</th>

                  <th>Severity</th>

                  <th>Anomaly</th>

                  <th>Activity</th>

                  <th>Action</th>

                </tr>

              </thead>

              <tbody>

                {currentLogs.map((log, index) => (

                  <tr
                    key={index}
                    className="border-b hover:bg-slate-50 transition"
                  >

                    <td className="py-4 font-medium">
                      {log.user}
                    </td>

                    <td>
                      {log.risk_score}
                    </td>

                    <td>

                      <span
                        className={`px-3 py-1 rounded-lg text-white ${badgeColor(
                          log.risk_level
                        )}`}
                      >
                        {log.risk_level}
                      </span>

                    </td>

                    <td>

                      <span
                        className={
                          log.anomaly === "Anomaly"
                            ? "text-red-600 font-semibold"
                            : "text-green-600 font-semibold"
                        }
                      >
                        {log.anomaly}
                      </span>

                    </td>

                    <td>

                      {log.reason_1}

                    </td>

                    <td>

                      <button
                        className="text-cyan-600 hover:underline"
                        onClick={() =>
                          alert(
                            `Activity Details\n\n${log.reason_1}`
                          )
                        }
                      >
                        View
                      </button>

                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          )}

        </div>

        {/* Pagination */}

        <div className="flex justify-between items-center mt-6">

          <button
            disabled={currentPage === 1}
            onClick={() =>
              setCurrentPage(currentPage - 1)
            }
            className="bg-gray-200 px-4 py-2 rounded disabled:opacity-50"
          >
            Previous
          </button>

          <span>
            Page {currentPage} of {totalPages}
          </span>

          <button
            disabled={currentPage === totalPages}
            onClick={() =>
              setCurrentPage(currentPage + 1)
            }
            className="bg-gray-200 px-4 py-2 rounded disabled:opacity-50"
          >
            Next
          </button>

        </div>

        <Footer />

      </div>
    </div>
  </div>
);
}