import React, { useState, useEffect } from 'react'
import { 
  Activity, AlertTriangle, RefreshCw, CheckCircle, ShieldAlert, 
  Cpu, Users, Filter, ArrowUpRight, Search, Eye, Shield, X, Download, UserX, Lock, AlertCircle
} from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import api from '../services/api'
import { PieChartComponent, BarChartComponent } from '../components/Charts'

const AnalyticsCockpit = () => {
  const [anomalies, setAnomalies] = useState([])
  const [baselines, setBaselines] = useState([])
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [scanning, setScanning] = useState(false)
  const [statusFilter, setStatusFilter] = useState('')
  const [severityFilter, setSeverityFilter] = useState('')
  const [scanMessage, setScanMessage] = useState('')
  const [selectedAnomaly, setSelectedAnomaly] = useState(null)
  const [actionFeedback, setActionFeedback] = useState('')

  const fetchAnalyticsData = async () => {
    try {
      setLoading(true)
      const [anomRes, baseRes, sumRes] = await Promise.all([
        api.get('/analytics/anomalies', { params: { status_filter: statusFilter, severity_filter: severityFilter } }),
        api.get('/analytics/baselines'),
        api.get('/analytics/summary')
      ])
      setAnomalies(anomRes.data)
      setBaselines(baseRes.data)
      setSummary(sumRes.data)
    } catch (err) {
      console.error("Failed to load analytics data", err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchAnalyticsData()
  }, [statusFilter, severityFilter])

  const handleRunScan = async () => {
    setScanning(true)
    setScanMessage('')
    try {
      const res = await api.post('/analytics/recalculate')
      setScanMessage(`Scan complete: ${res.data.metrics.baselines_updated} baselines calculated, ${res.data.metrics.anomalies_created} new anomalies flagged.`)
      await fetchAnalyticsData()
    } catch (err) {
      setScanMessage("Failed to execute behavioral scan.")
    } finally {
      setScanning(false)
    }
  }

  const handleUpdateStatus = async (anomalyId, newStatus) => {
    try {
      await api.put(`/analytics/anomalies/${anomalyId}/status`, { status: newStatus })
      fetchAnalyticsData()
      if (selectedAnomaly && selectedAnomaly.id === anomalyId) {
        setSelectedAnomaly(prev => ({ ...prev, status: newStatus }))
      }
    } catch (err) {
      alert("Failed to update status")
    }
  }

  const handleBlockUser = async (anomalyId) => {
    if (!window.confirm("Are you sure you want to deactivate and block this employee's access clearance?")) return
    try {
      const res = await api.post(`/analytics/anomalies/${anomalyId}/action`, { action_type: 'block_user' })
      setActionFeedback(res.data.message)
      fetchAnalyticsData()
      setTimeout(() => setActionFeedback(''), 4000)
    } catch (err) {
      alert("Failed to execute user block action")
    }
  }

  const handleExportEvidence = (anom) => {
    const textContent = `========================================================
INSIDER THREAT INCIDENT EVIDENCE REPORT
========================================================
Incident ID      : #ANOM-${anom.id}
Timestamp        : ${new Date(anom.created_at).toLocaleString()}
Subject Name     : ${anom.employee ? anom.employee.name : 'System Entity'}
Subject Email    : ${anom.employee ? anom.employee.email : 'N/A'}
Subject Position : ${anom.employee ? anom.employee.designation : 'N/A'}
Anomaly Category : ${anom.category}
Threat Severity  : ${anom.severity}
IsolationForest Score : ${anom.anomaly_score} (Scale: 0.0 - 1.0)
Investigation Status  : ${anom.status}

--------------------------------------------------------
INCIDENT DESCRIPTION:
${anom.description}

--------------------------------------------------------
TECHNICAL EVIDENCE PAYLOAD:
${JSON.stringify(anom.details || {}, null, 2)}

--------------------------------------------------------
REPORT GENERATED BY INSIDERTHREAT.AI BEHAVIORAL ENGINE
========================================================`

    const element = document.createElement("a")
    const file = new Blob([textContent], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = `incident_evidence_anom_${anom.id}_${Date.now()}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  if (loading && !anomalies.length) {
    return (
      <div style={{ color: 'var(--text-secondary)', padding: '3rem', textAlign: 'center' }}>
        <h2>Loading Behavioral Analytics Engine...</h2>
      </div>
    )
  }

  return (
    <div className="main-content">
      {/* Header Banner */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h1 style={{ fontSize: '2.25rem', fontFamily: 'Space Grotesk', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.75rem', color: 'var(--text-primary)' }}>
            <Activity style={{ color: 'var(--accent-blue)' }} /> BEHAVIORAL ANALYTICS & ANOMALY COCKPIT
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>
            Scikit-Learn IsolationForest outlier detection & real-time threat investigation workflows
          </p>
        </div>

        <button 
          onClick={handleRunScan} 
          className="btn btn-primary" 
          disabled={scanning}
          style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', padding: '0.75rem 1.25rem' }}
        >
          <RefreshCw size={18} className={scanning ? 'spinner' : ''} />
          {scanning ? 'Running ML Anomaly Scan...' : 'Trigger ML Behavioral Scan'}
        </button>
      </div>

      {scanMessage && (
        <div className="alert alert-success" style={{ marginBottom: '2rem' }}>
          {scanMessage}
        </div>
      )}

      {actionFeedback && (
        <div className="alert alert-danger" style={{ marginBottom: '2rem' }}>
          {actionFeedback}
        </div>
      )}

      {/* Summary Metric Cards */}
      {summary && (
        <div className="dashboard-grid" style={{ marginBottom: '2.5rem' }}>
          <div className="glass-card stat-card">
            <div>
              <span className="stat-label">Total Flagged Anomalies</span>
              <div className="stat-value" style={{ color: 'var(--color-danger)' }}>{summary.total_anomalies}</div>
            </div>
            <div className="stat-icon" style={{ backgroundColor: 'rgba(220, 38, 38, 0.08)', color: 'var(--color-danger)' }}>
              <AlertTriangle size={24} />
            </div>
          </div>

          <div className="glass-card stat-card">
            <div>
              <span className="stat-label">Open Triage Queue</span>
              <div className="stat-value" style={{ color: 'var(--color-warning)' }}>{summary.open_anomalies}</div>
            </div>
            <div className="stat-icon" style={{ backgroundColor: 'rgba(217, 119, 6, 0.08)', color: 'var(--color-warning)' }}>
              <ShieldAlert size={24} />
            </div>
          </div>

          <div className="glass-card stat-card">
            <div>
              <span className="stat-label">High / Critical Threats</span>
              <div className="stat-value" style={{ color: 'var(--color-critical)' }}>
                {(summary.severity_distribution.Critical || 0) + (summary.severity_distribution.High || 0)}
              </div>
            </div>
            <div className="stat-icon" style={{ backgroundColor: 'rgba(185, 28, 28, 0.08)', color: 'var(--color-critical)' }}>
              <Activity size={24} />
            </div>
          </div>

          <div className="glass-card stat-card">
            <div>
              <span className="stat-label">ML Model Engine</span>
              <div className="stat-value" style={{ color: 'var(--color-success)', fontSize: '1.25rem', marginTop: '0.5rem' }}>
                IsolationForest (Ready)
              </div>
            </div>
            <div className="stat-icon" style={{ backgroundColor: 'rgba(5, 150, 105, 0.08)', color: 'var(--color-success)' }}>
              <Cpu size={24} />
            </div>
          </div>
        </div>
      )}

      {/* Main Content Layout: Anomalies Triage Panel & Behavioral Baselines */}
      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '2rem', marginBottom: '2.5rem' }}>
        
        {/* Anomalies List */}
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
            <h3 style={{ fontFamily: 'Space Grotesk', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <ShieldAlert size={20} /> Detected Behavioral Anomalies ({anomalies.length})
            </h3>

            {/* Filter controls */}
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <select 
                value={statusFilter} 
                onChange={(e) => setStatusFilter(e.target.value)}
                className="form-control"
                style={{ width: 'auto', padding: '0.4rem 2rem 0.4rem 0.75rem', fontSize: '0.825rem' }}
              >
                <option value="">All Statuses</option>
                <option value="Open">Open</option>
                <option value="Investigating">Investigating</option>
                <option value="Triaged">Triaged</option>
                <option value="Closed">Closed</option>
              </select>

              <select 
                value={severityFilter} 
                onChange={(e) => setSeverityFilter(e.target.value)}
                className="form-control"
                style={{ width: 'auto', padding: '0.4rem 2rem 0.4rem 0.75rem', fontSize: '0.825rem' }}
              >
                <option value="">All Severities</option>
                <option value="Critical">Critical</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
              </select>
            </div>
          </div>

          <div className="table-container">
            <table className="custom-table" style={{ fontSize: '0.85rem' }}>
              <thead>
                <tr>
                  <th>Timestamp</th>
                  <th>Employee / Subject</th>
                  <th>Anomaly Category</th>
                  <th>Severity</th>
                  <th>Score</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {anomalies.length === 0 ? (
                  <tr>
                    <td colSpan="7" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                      No anomalies flagged for current filter selection.
                    </td>
                  </tr>
                ) : (
                  anomalies.map(anom => (
                    <tr key={anom.id}>
                      <td style={{ whiteSpace: 'nowrap', color: 'var(--text-muted)' }}>
                        {new Date(anom.created_at).toLocaleTimeString()}
                      </td>
                      <td style={{ fontWeight: '600' }}>
                        {anom.employee ? (
                          <Link to={`/employees/${anom.employee.id}`} style={{ color: 'var(--text-primary)', textDecoration: 'none' }}>
                            {anom.employee.name}
                          </Link>
                        ) : 'System Entity'}
                      </td>
                      <td>
                        <span style={{ fontWeight: '600', color: 'var(--text-primary)' }}>{anom.category}</span>
                        <div style={{ fontSize: '0.775rem', color: 'var(--text-secondary)', marginTop: '0.15rem' }}>
                          {anom.description}
                        </div>
                      </td>
                      <td>
                        <span className={`badge badge-${anom.severity.toLowerCase()}`}>
                          {anom.severity}
                        </span>
                      </td>
                      <td style={{ fontWeight: 'bold', color: anom.anomaly_score > 0.8 ? 'var(--color-danger)' : 'var(--color-warning)' }}>
                        {anom.anomaly_score}
                      </td>
                      <td>
                        <select 
                          value={anom.status} 
                          onChange={(e) => handleUpdateStatus(anom.id, e.target.value)}
                          style={{
                            padding: '0.2rem 0.4rem',
                            borderRadius: '6px',
                            fontSize: '0.75rem',
                            fontWeight: '700',
                            backgroundColor: anom.status === 'Open' ? '#fee2e2' : anom.status === 'Investigating' ? '#e0f2fe' : anom.status === 'Triaged' ? '#fef3c7' : '#d1fae5',
                            color: anom.status === 'Open' ? '#b91c1c' : anom.status === 'Investigating' ? '#0369a1' : anom.status === 'Triaged' ? '#b45309' : '#047857',
                            border: '1px solid var(--border-color)',
                            cursor: 'pointer'
                          }}
                        >
                          <option value="Open">Open</option>
                          <option value="Investigating">Investigating</option>
                          <option value="Triaged">Triaged</option>
                          <option value="Closed">Closed</option>
                        </select>
                      </td>
                      <td>
                        <div style={{ display: 'flex', gap: '0.35rem', flexWrap: 'wrap' }}>
                          <button 
                            onClick={() => setSelectedAnomaly(anom)}
                            className="btn btn-secondary" 
                            style={{ padding: '0.25rem 0.55rem', fontSize: '0.75rem', display: 'inline-flex', alignItems: 'center', gap: '0.25rem' }}
                            title="View technical evidence payload & response options"
                          >
                            <Eye size={12} /> Investigate
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Behavioral Baselines Panel & Threat Severity Pie Chart */}
        <div className="glass-card">
          {summary && (
            <div style={{ marginBottom: '1.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1.25rem' }}>
              <h3 style={{ fontFamily: 'Space Grotesk', marginBottom: '1rem', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <ShieldAlert size={18} /> Threat Severity Pie Chart
              </h3>
              <PieChartComponent 
                title="Severity"
                data={[
                  { label: 'Critical', value: summary.severity_distribution.Critical || 0, color: 'var(--color-critical)' },
                  { label: 'High', value: summary.severity_distribution.High || 0, color: 'var(--color-danger)' },
                  { label: 'Medium', value: summary.severity_distribution.Medium || 0, color: 'var(--color-warning)' },
                  { label: 'Low', value: summary.severity_distribution.Low || 0, color: 'var(--color-success)' }
                ]}
              />
            </div>
          )}

          <h3 style={{ fontFamily: 'Space Grotesk', marginBottom: '1.25rem', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Users size={18} /> Employee Baselines
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxHeight: '600px', overflowY: 'auto' }}>
            {baselines.map(b => (
              <div 
                key={b.id} 
                style={{ 
                  backgroundColor: 'var(--bg-tertiary)', 
                  border: '1px solid var(--border-color)', 
                  borderRadius: '10px', 
                  padding: '1rem' 
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                  <span style={{ fontWeight: '600', color: 'var(--text-primary)' }}>
                    {b.employee ? b.employee.name : `Employee #${b.employee_id}`}
                  </span>
                  <span style={{ fontSize: '0.75rem', color: 'var(--accent-cyan)', backgroundColor: 'rgba(2, 132, 199, 0.08)', padding: '0.15rem 0.5rem', borderRadius: '6px', fontWeight: '600', border: '1px solid rgba(2, 132, 199, 0.2)' }}>
                    {b.employee ? b.employee.designation : 'Staff'}
                  </span>
                </div>

                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                  <div>Daily Logins: <strong style={{ color: 'var(--text-primary)' }}>{b.avg_daily_logins}</strong></div>
                  <div>Off-Hours Ratio: <strong style={{ color: b.after_hours_ratio > 0.3 ? 'var(--color-warning)' : 'var(--text-primary)' }}>{(b.after_hours_ratio * 100).toFixed(0)}%</strong></div>
                  <div>Avg Downloads: <strong style={{ color: 'var(--text-primary)' }}>{b.avg_daily_downloads} MB</strong></div>
                  <div>USB Mounts: <strong style={{ color: b.usb_usage_count > 0 ? 'var(--color-danger)' : 'var(--text-primary)' }}>{b.usb_usage_count}</strong></div>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Investigation & Incident Response Modal */}
      {selectedAnomaly && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%',
          backgroundColor: 'rgba(15, 23, 42, 0.65)',
          backdropFilter: 'blur(4px)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1000
        }}>
          <div style={{
            width: '100%',
            maxWidth: '650px',
            backgroundColor: 'var(--bg-secondary)',
            border: '1px solid var(--border-color)',
            borderRadius: '12px',
            padding: '2rem',
            boxShadow: '0 20px 25px -5px rgba(0,0,0,0.2)',
            maxHeight: '90vh',
            overflowY: 'auto'
          }}>
            {/* Modal Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' }}>
              <div>
                <span style={{ fontSize: '0.8rem', textTransform: 'uppercase', color: 'var(--accent-blue)', fontWeight: '700' }}>
                  Incident Case #ANOM-{selectedAnomaly.id}
                </span>
                <h3 style={{ fontFamily: 'Space Grotesk', fontSize: '1.25rem', marginTop: '0.2rem' }}>
                  {selectedAnomaly.category}
                </h3>
              </div>
              <button onClick={() => setSelectedAnomaly(null)} style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer' }}>
                <X size={20} />
              </button>
            </div>

            {/* Incident Summary Badges */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
              <div style={{ backgroundColor: 'var(--bg-tertiary)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Threat Severity</span>
                <div style={{ marginTop: '0.25rem' }}>
                  <span className={`badge badge-${selectedAnomaly.severity.toLowerCase()}`}>
                    {selectedAnomaly.severity}
                  </span>
                </div>
              </div>

              <div style={{ backgroundColor: 'var(--bg-tertiary)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>IsolationForest Risk Score</span>
                <div style={{ fontSize: '1.1rem', fontWeight: 'bold', color: selectedAnomaly.anomaly_score > 0.8 ? 'var(--color-danger)' : 'var(--color-warning)', marginTop: '0.25rem' }}>
                  {selectedAnomaly.anomaly_score} / 1.0
                </div>
              </div>

              <div style={{ backgroundColor: 'var(--bg-tertiary)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-secondary)' }}>Current Status</span>
                <div style={{ marginTop: '0.25rem' }}>
                  <select 
                    value={selectedAnomaly.status}
                    onChange={(e) => handleUpdateStatus(selectedAnomaly.id, e.target.value)}
                    style={{ padding: '0.2rem 0.4rem', borderRadius: '4px', fontSize: '0.8rem', fontWeight: '600', border: '1px solid var(--border-color)' }}
                  >
                    <option value="Open">Open</option>
                    <option value="Investigating">Investigating</option>
                    <option value="Triaged">Triaged</option>
                    <option value="Closed">Closed</option>
                  </select>
                </div>
              </div>
            </div>

            {/* Description */}
            <div style={{ marginBottom: '1.5rem' }}>
              <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Incident Description</h4>
              <p style={{ backgroundColor: 'var(--bg-tertiary)', padding: '0.85rem', borderRadius: '8px', border: '1px solid var(--border-color)', fontSize: '0.9rem', color: 'var(--text-primary)' }}>
                {selectedAnomaly.description}
              </p>
            </div>

            {/* Technical Evidence Payload JSON */}
            <div style={{ marginBottom: '1.5rem' }}>
              <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Technical Evidence Payload</h4>
              <pre style={{
                backgroundColor: '#0f172a',
                color: '#38bdf8',
                padding: '1rem',
                borderRadius: '8px',
                fontSize: '0.825rem',
                fontFamily: 'monospace',
                overflowX: 'auto',
                border: '1px solid var(--border-color)'
              }}>
                {JSON.stringify(selectedAnomaly.details || {}, null, 2)}
              </pre>
            </div>

            {/* Response Action Buttons */}
            <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'flex-end', flexWrap: 'wrap', borderTop: '1px solid var(--border-color)', paddingTop: '1.25rem' }}>
              <button 
                onClick={() => handleExportEvidence(selectedAnomaly)}
                className="btn btn-secondary" 
                style={{ fontSize: '0.85rem' }}
              >
                <Download size={15} /> Export Evidence Report (.txt)
              </button>

              {selectedAnomaly.employee && (
                <button 
                  onClick={() => handleBlockUser(selectedAnomaly.id)}
                  className="btn btn-danger" 
                  style={{ fontSize: '0.85rem' }}
                >
                  <UserX size={15} /> Block Subject Clearance
                </button>
              )}

              <button 
                onClick={() => setSelectedAnomaly(null)}
                className="btn btn-primary" 
                style={{ fontSize: '0.85rem' }}
              >
                Done
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  )
}

export default AnalyticsCockpit
