import { useEffect, useState } from "react";
import { getAlerts } from "../services/alertService";

import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

import "../styles/dashboard.css";

function ThreatAlerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAlerts();
  }, []);

  const fetchAlerts = async () => {
    try {
      const data = await getAlerts();
      setAlerts(data);
    } catch (error) {
      console.error("Error loading alerts:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="dashboard-container">
      <Sidebar />

      <div className="main-content">
        <Navbar />

        <div className="dashboard-body">
          <div className="dashboard-header mb-4">
            <h2>Threat Alerts</h2>
            <p>
              View all detected insider threat alerts generated by the AI
              Behaviour Intelligence System.
            </p>
          </div>

          <div className="card shadow-sm">
            <div className="card-body">
              <h4 className="mb-4">🚨 Recent Threat Alerts</h4>

              {loading ? (
                <div className="text-center py-4">
                  <div
                    className="spinner-border text-primary"
                    role="status"
                  >
                    <span className="visually-hidden">Loading...</span>
                  </div>

                  <p className="mt-3">Loading alerts...</p>
                </div>
              ) : alerts.length === 0 ? (
                <div className="alert alert-info">
                  No threat alerts found.
                </div>
              ) : (
                alerts.map((alert) => (
                  <div
                    className="alert-item"
                    key={alert.employee_id}
                  >
                    <div
                      className={`alert-level alert-${alert.risk_level.toLowerCase()}`}
                    >
                      {alert.risk_level}
                    </div>

                    <div className="alert-content">
                      <h5>{alert.message}</h5>

                      <p>
                        <strong>Employee ID:</strong>{" "}
                        {alert.employee_id}
                      </p>

                      <p>
                        <strong>Risk Score:</strong>{" "}
                        {alert.risk_score}
                      </p>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default ThreatAlerts;